package org.jboss.gpse.jaxb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-11-04T22:44:53.848-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "urn:org.jboss.gpse:1.0", name = "SimpleJaxWsService")
@XmlSeeAlso({ObjectFactory.class})
public interface SimpleJaxWsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "acceptSMS", targetNamespace = "urn:org.jboss.gpse:1.0", className = "org.jboss.gpse.jaxb.AcceptSMS")
    @WebMethod
    @ResponseWrapper(localName = "acceptSMSResponse", targetNamespace = "urn:org.jboss.gpse:1.0", className = "org.jboss.gpse.jaxb.AcceptSMSResponse")
    public org.jboss.gpse.jaxb.SmsResponse acceptSMS(
        @WebParam(name = "arg0", targetNamespace = "")
        org.jboss.gpse.jaxb.Sms arg0
    );
}
