package org.jboss.gpse.jaxb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-11-04T22:44:53.893-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "SimpleJaxWsService", 
                  wsdlLocation = "http://zareason:8080/pfp-simpleJaxWs/SimpleJaxWsService?wsdl",
                  targetNamespace = "urn:org.jboss.gpse:1.0") 
public class SimpleJaxWsService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:org.jboss.gpse:1.0", "SimpleJaxWsService");
    public final static QName SimpleJaxWsPort = new QName("urn:org.jboss.gpse:1.0", "SimpleJaxWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://zareason:8080/pfp-simpleJaxWs/SimpleJaxWsService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SimpleJaxWsService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://zareason:8080/pfp-simpleJaxWs/SimpleJaxWsService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SimpleJaxWsService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleJaxWsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleJaxWsService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SimpleJaxWsService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SimpleJaxWsService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SimpleJaxWsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SimpleJaxWsService
     */
    @WebEndpoint(name = "SimpleJaxWsPort")
    public SimpleJaxWsService getSimpleJaxWsPort() {
        return super.getPort(SimpleJaxWsPort, SimpleJaxWsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleJaxWsService
     */
    @WebEndpoint(name = "SimpleJaxWsPort")
    public SimpleJaxWsService getSimpleJaxWsPort(WebServiceFeature... features) {
        return super.getPort(SimpleJaxWsPort, SimpleJaxWsService.class, features);
    }

}
